### ISSUE TITLE
run it in a local machine

### ISSUE THREAD

**Issue by developerfranso** [hennes-maertins/read-a-meter#3]
greetings how do i run it in a local machine

**Comment by hennes-maertins** [comment]
Hello developerfranso,

thank you for your interest in this project. The Android Package is build by [PhoneGab Build](https://build.phonegap.com). This build is configured by the file `config.xml`.

Indeed a configuration for a local build of an apk file is missing completely at the moment. If you want to test the functionality of this app on your local machine you can open the file `index.html` in the directory `www` with a web browser (e.g. firefox). Because the app is based on html+css+js without any specific android device features that should be enough for a first glance.

Nonetheless it's a very good idea to extend the build configuration of this PhoneGap project so that you can build the apk file on your local machine. I assume that the following steps need to be implemented to fulfil this issue:
- Add android to the PhoneGap platforms of this project (`phonegap platform add android`).
- Run app in emulator successfully (`phonegap run android`).
- Finish a local build of the apk file (`phonegap build android`) and test this file on a real device.
- Write into the `README.md` how to build and run the app and the requirements of the local machine (installed phonegap, android sdk, etc.).

I will implement this issue in future.

Thank you for your contribution to this project. :-)

**Comment by hennes-maertins** [comment]
The README.md has been extended. It contains instructions to
- run the app locally in your browser,
- build it as an android app,
- test it on a real device by using `phonegap serve`.

The README.md contains no instructions to run the app on an emulated device on the local machine. This is not needed because you can run it faster in a web browser.
